name: CI

on:
  # Trigger on all pushes and PRs
  push:
  pull_request:

  # Allow manually running workflow
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          sudo apt-get install -y mingw-w64 libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev
      - name: Build
        run: |
          make linux
      - name: Upload Linux build
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./bin/release

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          sudo apt-get install -y git python3 cmake
      - name: Setup emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git pull
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..
      - name: Build
        run: |
          source ./emsdk/emsdk_env.sh
          make web
      - name: Upload Web build
        uses: actions/upload-artifact@v2
        with:
          name: emscripten
          path: ./emscripten
